language: php
php:
  - 5.4
  - 5.5
  - 5.6

branches:
  except:
    - share

env:
    - DB=sqlite
    - DB=mysql
#  - DB=pgsql

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh contacts stable8 $DB

#  - sudo add-apt-repository -y ppa:chris-lea/node.js
#  - sudo apt-get update
#  - sudo apt-get -y install nodejs
#  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2
#  - tar xjf phantomjs-1.9.0-linux-x86_64.tar.bz2
#  - sudo ln -s $(pwd)/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

script:
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"
  - phpunit --configuration tests/phpunit.xml --testsuite unit-tests

#&& make javascript-tests
